language: c

install: true

group: "stable"

script: echo Travis

stage: build

branches:
  only:
    - master

jobs:
  include:
    - stage: build
    - script: make -C lab6/hello all
  include:
    - stage: test
    - script: lab6/hello/hello

